### ISSUE TITLE
ValueToSet cant set empty value

### ISSUE THREAD

**Issue by nbt11nsn** [BizTalkComponents/ContextRegExReplace#2]
When trying to replace a value with empty value the pipeline doesnt approve. For example, if i have a file with the name XXXX.csv and want to remove ".csv" so it looks like "XXXX". Then the pipeline tells me that ValueToSet needs to have a value and cannot be empty.

**Comment by robinhultman** [comment]
Removed the required attribute for ValueToSet in release 1.6.0.0.
